# Generated by Django 2.0.2 on 2018-09-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180929_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='exitOfEmployment',
            field=models.DateField(blank=True, verbose_name='Salida de Empleo'),
        ),
    ]
