# Generated by Django 2.0.2 on 2018-09-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180929_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='exitOfEmployment',
            field=models.DateField(null=True, verbose_name='Salida de Empleo'),
        ),
    ]
