# Generated by Django 2.0.2 on 2018-10-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20181006_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectportfolio',
            old_name='exitOfEmployment',
            new_name='exitproject',
        ),
        migrations.RenameField(
            model_name='projectportfolio',
            old_name='startOfEmployment',
            new_name='startproject',
        ),
    ]
