# Generated by Django 2.0.2 on 2018-10-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20181006_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectportfolio',
            name='urlproject',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Url'),
        ),
    ]
