# Generated by Django 2.0.2 on 2018-10-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttrayectoria',
            name='exitOfEmployment',
            field=models.DateField(blank=True, null=True, verbose_name='Salida de Empleo'),
        ),
        migrations.AddField(
            model_name='projecttrayectoria',
            name='startOfEmployment',
            field=models.DateField(default='2018-01-01', verbose_name='Inicio de Empleo'),
            preserve_default=False,
        ),
    ]
