# Generated by Django 2.0.2 on 2018-10-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0002_auto_20181006_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttrayectoria',
            name='image',
            field=models.ImageField(upload_to='projectstrayectoria', verbose_name='Avatar'),
        ),
    ]
