# Generated by Django 2.0.2 on 2018-10-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFormacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('especialidad', models.CharField(max_length=350, verbose_name='Especialidad')),
                ('institucion', models.CharField(max_length=350, verbose_name='Institución')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('graduacion', models.IntegerField(verbose_name='Año de Graduacion')),
                ('muestragraduacion', models.BooleanField(default=True, verbose_name='¿Mostrar Año de Graduación?')),
                ('notaadicional', models.TextField(blank=True, null=True, verbose_name='Nota Adicional')),
                ('image', models.ImageField(upload_to='projectsformacion', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'formación',
                'verbose_name_plural': 'formaciones',
                'ordering': ['-created'],
            },
        ),
    ]
